### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by TiberiumPY** [spiffy/spiffy#7]
PyPy currently does not support CPython 3.5 (but Mozilla donated $200000 to PyPy for CPython 3.5 support).
Also, is there any chances that you could add Python 2 support?

**Comment by mhsjlw** [comment]
We will definitely not be adding Python 2.7 support as Python 3.5 is much better suited for the networking/protocol prototyping that will be done in Spiffy. If you're interested in running it under Python 2.7 you may try the `2to3` utility, although it's unlikely it will work as all of our deps and our deps deps are Python 3.5

**Comment by TiberiumPY** [comment]
And, about TODO in your code (world.py) - if PyPy will support CPython 3.5, there'll be no need to use C-extensions.

**Comment by mhsjlw** [comment]
We're looking for a speed up using C extensions, that is why I left the comment in the code.
